 # Stage 1: Build with Maven
FROM maven:3.9.4-eclipse-temurin-17-alpine AS builder
WORKDIR /app
COPY . .
RUN mvn clean install -N && mvn clean install -pl buildpro-eureka-server -am -DskipTests


# Stage 2: Run with JDK
FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY --from=builder /app/buildpro-eureka-server/target/buildpro-eureka-server-*.jar app.jar
EXPOSE 8761
ENTRYPOINT ["java", "-jar", "app.jar"]
