server:
  port: 8082

spring:
  application:
    name: product-service

  security:
    user:
      name: admin
      password: admin

  datasource:
    url: jdbc:postgresql://ep-orange-queen-a1j77snw-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_qYj5eEy6mDXN
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

