server:
  port:  ${PORT:8761}

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://buildpro-eureka-server.onrender.com/eureka/

  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:buildpro-eureka-server.onrender.com}
    prefer-ip-address: false

  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
