server:
  port: ${PORT:8081}

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://ep-orange-queen-a1j77snw-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_qYj5eEy6mDXN
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password   ⚠️ Replace with the Gmail app password (not your Gmail login password)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://buildpro-eureka-server.onrender.com/eureka/
